---
title: "reproducible project 1"
author: "Nsovo Ntuli"
date: "2023-10-21"
output:
  pdf_document: default
  html_document: default
---


```{r}
library("tidyverse")
```

```{r}
#url link of the project
url <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
```

```{r}
#path to save the project file

local_file <- "R"
```

```{r}
#download the poject file
download.file(url, local_file, mode = "wb")
```

```{r}
#unzip the file

unzip(local_file, exdir = "url")
```

```{r}
#import the activity.csv file
activity <- read_csv("url/activity.csv")
```


```{r}
library("rmarkdown")
```


```{r}
library("knitr")
```


```{r}
# question 1 Calculate the total number of steps taken per day
stepsPerDay <- activity %>%
        group_by(date) %>%
        summarize(sumsteps = sum(steps, na.rm = TRUE)) 
#Display first 10 rows of data
head(stepsPerDay,10)
```
`
```{r}
#question 2 Make a histogram of the total number of steps taken each day.
hist(stepsPerDay$sumsteps, main = "Histogram of Daily Steps", 
     col="green", xlab="Steps", ylim = c(0,30))
```

```{r}

#queston 3: Calculate and report the mean and median of the total number of steps taken per day

mean_before_NA <- round(mean(stepsPerDay$sumsteps),digits = 2)
median_before_NA <- round(median(stepsPerDay$sumsteps),digits = 2)

print(paste("The mean is: ", mean_before_NA))

print(paste("The median is: ", median_before_NA))

```

What is the average daily activity pattern

```{r}
#question 1: Make a time series plot (i.e. type = “l”|) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis).

stepsPerInterval <- activity %>%
        group_by(interval) %>%
        summarize(meansteps = mean(steps, na.rm = TRUE)) 
#Display first 10 rows of data
head(stepsPerInterval,10)
```

```{r}
plot(stepsPerInterval$meansteps ~ stepsPerInterval$interval,
     col="brown", type="l", xlab = "5 Minute Intervals", ylab = "Average Number of Steps",
     main = "Steps By Time Interval")

```

```{r}
# question 2: Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

print(paste("Interval containing the most steps on average: ",stepsPerInterval$interval[which.max(stepsPerInterval$meansteps)]))

print(paste("Average steps for that interval: ",round(max(stepsPerInterval$meansteps),digits=2)))
```
calculation of missing values 
```{r}
#question 1: Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)
print(paste("The total number of rows with NA is: ",sum(is.na(activity$steps))))
```
```{r}
##question 2:Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.

 answer Filling in missing values in a dataset is an important step in data preprocessing. While the choice of strategy depends on the specific characteristics of your data and the nature of the missing values, here's a simple strategy that you can consider:


Group Data by Hour: If your dataset includes a timestamp or date-time variable, you can start by grouping the data by the hour of the day. This can be done using date-time functions or libraries in R.

Calculate the Mean: For each hourly group, calculate the mean of the available values within that hour. You can use the dplyr package to do this
```


```{r}
#question 3:Create a new dataset that is equal to the original dataset but with the missing data filled in.

#Before 
#Display first 10 rows of data
head(activity,10)
```
```{r}
activityNoNA <- activity  
for (i in 1:nrow(activity)){
        if(is.na(activity$steps[i])){
                activityNoNA$steps[i]<- stepsPerInterval$meansteps[activityNoNA$interval[i] == stepsPerInterval$interval]
        }
}

#After
#Display first 10 rows of data
head(activityNoNA,10)
```

```{r}
#question 4: Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

stepsPerDay <- activityNoNA %>%
        group_by(date) %>%
        summarize(sumsteps = sum(steps, na.rm = TRUE)) 
head(stepsPerDay,10)
```
```{r}
hist(stepsPerDay$sumsteps, main = "Histogram of Daily Steps", 
     col="skyblue", xlab="Steps")
```

```{r}
mean_after_NA <- round(mean(stepsPerDay$sumsteps), digits = 2)
median_after_NA <- round(median(stepsPerDay$sumsteps), digits = 2)

print(paste("The mean is: ", mean(mean_after_NA)))
print(paste("The median is: ", median(median_after_NA)))
```
```{r}
#compare the meamn and meadian before the missing values(NA) and after the missing values(NA)

NACompare <- data.frame(mean = c(mean_before_NA,mean_after_NA),median = c(median_before_NA,median_after_NA))
rownames(NACompare) <- c("before NA Transformation", "after NA Transformation")
print(NACompare)
```


Are there differences in activity patterns between weekdays and weekends?

```{r}
#question 1:Create a new factor variable in the dataset with two levels - “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.

activityDoW <- activityNoNA
activityDoW$date <- as.Date(activityDoW$date)
activityDoW$day <- ifelse(weekdays(activityDoW$date) %in% c("Saturday", "Sunday"), "weekend", "weekday")
activityDoW$day <- as.factor(activityDoW$day)
```

```{r}
#question 2: Make a panel plot containing a time series plot (i.e. type=“l”) of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis).

activityWeekday <- filter(activityDoW, activityDoW$day == "weekday")
activityWeekend <- filter(activityDoW, activityDoW$day == "weekend")

activityWeekday <- activityWeekday %>%
        group_by(interval) %>%
        summarize(steps = mean(steps)) 
activityWeekday$day <- "weekday"

activityWeekend <- activityWeekend %>%
        group_by(interval) %>%
        summarize(steps = mean(steps)) 
activityWeekend$day <- "weekend"

wkdayWkend <- rbind(activityWeekday, activityWeekend)
wkdayWkend$day <- as.factor(wkdayWkend$day)


g <- ggplot (wkdayWkend, aes (interval, steps))
g + geom_line() + facet_grid (day~.) + 
        theme(axis.text = element_text(size = 12),axis.title = element_text(size = 14)) + 
        labs(y = "Number of Steps") + labs(x = "Interval") + 
        ggtitle("Average Number of Steps - Weekday vs. Weekend") + 
        theme(plot.title = element_text(hjust = 0.5))
```







